### PR TITLE
Add paused to retry state

### PR DESCRIPTION
**Pull request by ychebotarev**
Add RETRY_STATE_PAUSED.

Part of activity API. If activity is paused, retry shouldn't happen, but we also shouldn't return an error. Thus we need another state.

This is what will be returned by RetryActivity in mutable state if activity is paused. I don't think it is visible outside of server code.

### CODE REVIEW

**Review by cretz — COMMENTED** [review]
Makes sense, I'm guessing we missed this one on #468. Do we want to wait to collect other things that we may add as part of this project for first implementation?

**Comment by ychebotarev** [comment]
> Makes sense, I'm guessing we missed this one on #468. Do we want to wait to collect other things that we may add as part of this project for first implementation?

This is not a breaking change.

**Comment by cretz** [comment]
Sorry, I mistyped, I mean #469. Yes, in this case it was good that what was missed is an addition and not a reworking.

**Comment by ychebotarev** [comment]
ok lets not do that.

**Pull request closed without merging**
