### PR TITLE
Support for SignalWithStartChildWorkflowExecutionCommandAttributesfr…

### PR DESCRIPTION
**Pull request by edmondop**
Expose https://github.com/temporalio/api/blob/master/temporal/api/workflowservice/v1/request_response.proto#LL615C9-L615C48 SignalWithStartWorkflow capability to the client

**Why?**

To avoid the current workaround of using Temporal client from activities

**Breaking changes**

### CODE REVIEW

**Comment by cretz** [comment]
I fear this implementation of this on the server is a larger challenge than just adding the API

**Comment by edmondop** [comment]
> I think the implementation of this on the server is a larger challenge than it may seem

Can you share more ?

**Comment by cretz** [comment]
Implementing a new command in the server and in every SDK is a non-trivial task and often it requires an accompanying event in workflow history. It can take a really long time to understand the code, and then a long time to implement it.

**Comment by edmondop** [comment]
> Implementing a new command in the server and in every SDK is a non-trivial task and often it requires an accompanying event in workflow history. It can take a really long time to understand the code, and then a long time to implement it.

I see, would you prefer to have at least the accompanying PR on the server side before merging this? I think SDK can wait longer to implement the feature that the server offers

**Comment by cretz** [comment]
Yes, I think the implementation should be worked on and understood before this part since the implementation will effect this. For example, you'll likely need an event. Warning, implementing a new command/event in the server is not easy.

**Pull request closed without merging**
